name: DragonRespawn
version: '${version}'
main: org.example.bedepay.dragonrespawn.DragonRespawn
api-version: '1.20'
description: A plugin to respawn the Ender Dragon with customizable respawn timer and announcements.
permissions:
  dragonrespawn.reload:
    description: Allows the player to reload the DragonRespawn configuration
    default: op